import {
  Archive,
  Award,
  BadgeIndianRupee,
  BookOpenCheck,
  Boxes,
  Calculator,
  CalendarHeart,
  CalendarRange,
  Circle,
  Clapperboard,
  Cpu,
  FileSignature,
  FolderOpen,
  GraduationCap,
  History,
  Inbox,
  IndianRupee,
  LayoutDashboard,
  ListChecks,
  MessageSquareHeart,
  Package,
  PackageCheck,
  PhoneCall,
  Printer,
  Quote,
  ReceiptIndianRupee,
  School,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Store,
  Truck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/** Explicit icon map (keeps the bundle small — never import * from lucide). */
const ICONS: Record<string, LucideIcon> = {
  Archive,
  Award,
  BadgeIndianRupee,
  BookOpenCheck,
  Boxes,
  Calculator,
  CalendarHeart,
  CalendarRange,
  Clapperboard,
  Cpu,
  FileSignature,
  FolderOpen,
  GraduationCap,
  History,
  Inbox,
  IndianRupee,
  LayoutDashboard,
  ListChecks,
  MessageSquareHeart,
  Package,
  PackageCheck,
  PhoneCall,
  Printer,
  Quote,
  ReceiptIndianRupee,
  School,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Store,
  Truck,
  Users,
  Wallet,
};

export function HqIcon({ name, className, strokeWidth = 1.6 }: { name: string; className?: string; strokeWidth?: number }) {
  const I = ICONS[name] ?? Circle;
  return <I className={className} strokeWidth={strokeWidth} aria-hidden />;
}
